Repository yansircc/payload-builder, pull requests merged in 2025-02, with the labels that each got.

#91 feat(83): tenant fields for site level settings parent issue
  src/app/(frontend)/layout.tsx
  src/collections/SiteSetting/index.ts
  src/endpoints/seed/index.ts
  src/globals/Favicon/Component.tsx
  src/payload-types.ts
  src/payload.config.ts
  src/plugins/index.ts
Labels: qa:blocked

#101 feat(37): feature dynamic popup builder
  bun.lock
  package.json
  src/app/(payload)/admin/importMap.js
  src/collections/Pages/hooks/updateChildPaths.ts
  src/collections/Popups/index.ts
  src/components/ColorPicker/index.tsx
  src/components/ColorPicker/styles.css
  src/components/Link/PopupLink.tsx
  src/components/Link/index.tsx
  src/components/ui/dialog.tsx
  src/fields/color.ts
  src/fields/link.ts
  src/fields/slug/index.ts
  src/payload-types.ts
  src/payload.config.ts
  src/plugins/index.ts
  tailwind.config.mjs
Labels: dev:resolved

#107 Feat/79—feature add more basic blocks to post editor
  src/blocks/ColumnBlock/RenderColumn.tsx
  src/blocks/ColumnBlock/config.ts
  src/blocks/CtaSimpleBlock/RenderCtaSimple.tsx
  src/blocks/CtaSimpleBlock/config.ts
  src/blocks/LinkPopupBlock/RenderLinkPopup.tsx
  src/blocks/LinkPopupBlock/components/InquiryPopup.tsx
  src/blocks/LinkPopupBlock/config.ts
  src/blocks/List/RenderList.tsx
  src/blocks/List/config.tsx
  src/blocks/RenderBlocks.tsx
  src/blocks/Table/RenderTable.tsx
  src/blocks/Table/config.ts
  src/blocks/VideoBlock/RenderVideo.tsx
  src/blocks/VideoBlock/config.ts
  src/collections/Pages/index.ts
  src/collections/Posts/index.ts
  src/components/Link/index.tsx
  src/components/RichText/index.tsx
  src/payload-types.ts
Labels: admin:approved

#125 fix: hooks for form validation
  src/hooks/form/formFieldValidation.ts
  src/hooks/form/validateFormName.ts
  src/hooks/form/validateFormWidth.ts
  src/payload-types.ts
  src/plugins/index.ts
Labels: qa:verified

#124 fix: live preview button is not working on Services page
  src/collections/Services/index.ts
Labels: admin:approved

#92 Feature - Add design system with predefined design styles
  bun.lock
  docs/DESIGN_SYSTEM.md
  package.json
  src/app/(frontend)/globals.css
  src/app/(frontend)/layout.tsx
  src/collections/DesignSystem/types.ts
  src/collections/Tenants/index.ts
  src/config/fonts.ts
  src/endpoints/seed/collections/tenants/index.ts
  src/payload-types.ts
  src/providers/DesignSystemProvider.tsx
  src/providers/Theme/InitTheme/index.tsx
  src/providers/index.tsx
  src/themes/index.ts
  tailwind.config.mjs
Labels: admin:approved

#123 feat(43): feature ai basic generation function
  .env.example
  bun.lock
  package.json
  src/app/(frontend)/next/ai/route.ts
  src/app/(payload)/admin/importMap.js
  src/app/api/ai/route.ts
  src/fields/ai/client/icons/index.tsx
  src/fields/ai/client/index.tsx
  src/fields/ai/client/nodes/AICommandNode.tsx
  src/fields/ai/server/index.ts
  src/fields/defaultLexical.ts
  src/utilities/ai.ts
Labels: qa:verified

#131 feat: icon select in admin
  bun.lock
  package.json
  src/app/(payload)/admin/importMap.js
  src/components/IconSelect/index.tsx
  src/components/IconSelect/styles.css
  src/components/ui/command.tsx
  src/components/ui/popover.tsx
  src/components/ui/tooltip.tsx
  src/fields/icon.ts
  src/fields/link.ts
  src/payload-types.ts
Labels: qa:verified

#138 Refactor: Improve Theme Configuration, Hero Components, and Responsive Design Enhancements
  docs/DESIGN_SYSTEM.md
  src/app/(frontend)/globals.css
  src/fields/link.ts
  src/heros/components/Hero1/Component.tsx
  src/heros/components/Hero115/Component.tsx
  src/heros/components/Hero12/Component.tsx
  src/heros/components/Hero24/Component.tsx
  src/heros/components/Hero25/Component.tsx
  src/heros/components/Hero25/config.ts
  src/heros/components/Hero3/Component.tsx
  src/heros/components/Hero32/Component.tsx
  src/heros/components/Hero32/config.ts
  src/heros/components/Hero34/Component.tsx
  src/heros/components/Hero45/Component.tsx
  src/heros/components/Hero5/Component.tsx
  src/heros/components/Hero6/Component.tsx
  src/heros/components/Hero7/Component.tsx
  src/heros/components/Hero8/Component.tsx
  src/heros/components/shared/ThemeEffect.tsx
  src/payload-types.ts
  src/providers/DesignSystemProvider.tsx
  src/themes/index.ts
  tailwind.config.mjs
Labels: qa:verified

#137 fix: remove api-key and grouping exist collections
  src/collections/Categories.ts
  src/collections/CustomCodes/index.ts
  src/collections/Media.ts
  src/collections/Pages/index.ts
  src/collections/Popups/index.ts
  src/collections/Posts/index.ts
  src/collections/Products/index.ts
  src/collections/Services/index.ts
  src/collections/SiteSetting/index.ts
  src/collections/Tenants/index.ts
  src/collections/Users/index.ts
  src/globals/Footer/config.ts
  src/globals/Header/config.ts
  src/globals/api-keys.ts
  src/hooks/aiGenerateText.ts
  src/payload-types.ts
  src/payload.config.ts
  src/plugins/index.ts
  src/utilities/ai.ts
Labels: qa:verified

#146 fix: add hooks when parent get deleted
  src/collections/Pages/hooks/deleteChildPages.ts
  src/collections/Pages/index.ts
Labels: qa:verified

#155 fix(about): added components stories about block
  src/blocks/About/components/About1/Component.tsx
  src/blocks/About/components/About2/Component.tsx
  src/blocks/About/components/About2/component.stories.tsx
  src/blocks/About/components/About3/Component.tsx
  src/blocks/About/components/About3/component.stories.tsx
  src/blocks/About/components/About4/Component.tsx
  src/blocks/About/components/About4/component.stories.tsx
  src/blocks/About/components/About5/Component.tsx
  src/blocks/About/components/About5/component.stories.tsx
  src/blocks/About/components/About6/Component.tsx
  src/blocks/About/components/About6/component.stories.tsx
  src/blocks/Contact/components/Contact1/Component.tsx
  src/blocks/Contact/components/Contact2/Component.tsx
  src/blocks/Contact/components/Contact2/component.stories.tsx
  src/blocks/Contact/components/Contact3/Component.tsx
  src/blocks/Contact/components/Contact3/component.stories.tsx
  src/blocks/Contact/components/Contact4/Component.tsx
  src/blocks/Contact/components/Contact4/component.stories.tsx
  src/blocks/Contact/components/Contact5/Component.tsx
  src/blocks/Contact/components/Contact5/component.stories.tsx
  src/blocks/Contact/components/Contact6/Component.tsx
  src/blocks/Contact/components/Contact6/component.stories.tsx
  src/blocks/Contact/components/Contact7/Component.tsx
  src/blocks/Contact/components/Contact7/component.stories.tsx
  src/blocks/Contact/components/Contact8/Component.tsx
  src/blocks/Contact/components/Contact8/component.stories.tsx
  src/components/Link/index.tsx
  src/components/ui/button.tsx
Labels: dev:resolved

#135 feat(132): enhancement page list optimization on backend
  bun.lock
  package.json
  src/app/(frontend)/[[...segments]]/page.tsx
  src/app/(frontend)/posts/[slug]/page.tsx
  src/app/(frontend)/products/[slug]/page.tsx
  src/app/(frontend)/services/[slug]/page.tsx
  src/app/(payload)/admin/importMap.js
  src/collections/Pages/components/cells/TitleCell.tsx
  src/collections/Pages/index.ts
  src/collections/Posts/index.ts
  src/collections/Products/index.ts
  src/collections/Services/index.ts
  src/fields/slug/fullPath/cell.tsx
  src/fields/slug/index.ts
  src/payload-types.ts
  src/utilities/getClientSideURL.ts
  src/utilities/getTenant.client.tsx
Labels: qa:verified

#145 fix: Failed to Save if All Scripts Removed
  src/collections/CustomCodes/index.ts
  src/components/PayloadRedirects/index.tsx
  src/globals/CustomCode/Component.tsx
  src/payload-types.ts
Labels: qa:verified

#148 fix(129): enhancement product page fields optimization
  bun.lock
  package.json
  src/app/(frontend)/products/[slug]/ImageGallery.tsx
  src/app/(frontend)/products/[slug]/page.tsx
  src/app/(frontend)/products/page.tsx
  src/app/(frontend)/services/[slug]/page.tsx
  src/app/(payload)/admin/importMap.js
  src/collections/Categories.ts
  src/collections/Posts/index.ts
  src/collections/Products/index.ts
  src/collections/Services/index.ts
  src/components/ui/tabs.tsx
  src/endpoints/seed/collections/categories/index.ts
  src/endpoints/seed/collections/products/index.ts
  src/endpoints/seed/collections/services/index.ts
  src/payload-types.ts
Labels: qa:verified

#196 feat(98): custom 404 page
  src/app/(frontend)/not-found.tsx
  src/collections/SiteSetting/index.ts
  src/components/NotFound/index.tsx
  src/globals/Favicon/Component.tsx
  src/payload-types.ts
Labels: qa:verified

#201 fix: update REST API endpoint on Post collection
  src/collections/Posts/index.ts
Labels: dev:need-check

#160 feat(54): add widget whatsapp
  src/app/(frontend)/layout.tsx
  src/app/(payload)/admin/importMap.js
  src/globals/Widget/components/Whatsapp/Component.tsx
Labels: qa:verified

#168 feat: add stories for Table Component and adjust theme of table
  src/blocks/Table/Component.stories.tsx
  src/blocks/Table/RenderTable.tsx
Labels: qa:verified

#157 feat: posts migration wordpress to cms
  bun.lock
  docs/WORDPRESS_MIGRATION_GUIDE.md
  package.json
  src/app/(payload)/admin/importMap.js
  src/app/api/wordpress-migration/lexical-converter.ts
  src/app/api/wordpress-migration/migration-service.ts
  src/app/api/wordpress-migration/route.ts
  src/app/api/wordpress-migration/types.ts
  src/app/api/wordpress-migration/wordpress-parser.ts
  src/blocks/Banner/Component.tsx
  src/blocks/HTML/RenderTable.tsx
  src/blocks/HTML/config.ts
  src/blocks/RenderBlocks.tsx
  src/collections/Pages/index.ts
  src/collections/Posts/index.ts
  src/components/Nav/WordpressMigration.tsx
  src/components/RichText/index.tsx
  src/components/views/WordpressMigration/DefaultRootView.client.tsx
  src/components/views/WordpressMigration/DefaultRootView.tsx
  src/payload-types.ts
  src/payload.config.ts
  src/themes/index.ts
  tailwind.config.mjs
Labels: qa:verified

#169 feat: add Video Block Components Story
  src/blocks/VideoBlock/Component.stories.tsx
  src/blocks/VideoBlock/RenderVideo.tsx
Labels: qa:verified
