Repository yansircc/payload-builder, pull requests merged in 2025-03, with the labels that each got.

#167 feat/add Story book for Feature Components
  .idea/workspace.xml
  src/blocks/Feature/components/Feature1/Component.tsx
  src/blocks/Feature/components/Feature10/Component.stories.tsx
  src/blocks/Feature/components/Feature10/Component.tsx
  src/blocks/Feature/components/Feature11/Component.stories.tsx
  src/blocks/Feature/components/Feature13/Component.stories.tsx
  src/blocks/Feature/components/Feature13/Component.tsx
  src/blocks/Feature/components/Feature14/Component.stories.tsx
  src/blocks/Feature/components/Feature14/Component.tsx
  src/blocks/Feature/components/Feature15/Component.stories.tsx
  src/blocks/Feature/components/Feature15/Component.tsx
  src/blocks/Feature/components/Feature2/Component.stories.tsx
  src/blocks/Feature/components/Feature2/Component.tsx
  src/blocks/Feature/components/Feature3/Component.stories.tsx
  src/blocks/Feature/components/Feature3/Component.tsx
  src/blocks/Feature/components/Feature5/Component.stories.tsx
  src/blocks/Feature/components/Feature5/Component.tsx
  src/blocks/Feature/components/Feature6/Component.stories.tsx
  src/blocks/Feature/components/Feature6/Component.tsx
  src/blocks/Feature/components/Feature7/Component.stories.tsx
  src/blocks/Feature/components/Feature7/Component.tsx
  src/blocks/shared/components/GenerateButton.tsx
Labels: qa:verified

#203 fix(LinkComponents): add link pop up stories
  src/blocks/LinkPopupBlock/Component.stories.tsx
  src/blocks/LinkPopupBlock/components/InquiryPopup.tsx
Labels: qa:verified

#220 feat(ContentComponent): add content storybook component
  src/blocks/Content/Component.stories.tsx
  src/blocks/Content/Component.tsx
Labels: admin:approved

#223 feat(ListComponent): add list story book component
  src/blocks/List/Component.stories.tsx
Labels: admin:approved

#212 Feat/banner storybook
  src/blocks/Banner/Component.stories.tsx
Labels: admin:rejected

#239 fix: theme selection to SSR
  src/app/(frontend)/[[...segments]]/page.client.tsx
  src/app/(frontend)/globals.css
  src/app/(frontend)/layout.tsx
  src/app/(frontend)/posts/[slug]/page.client.tsx
  src/app/(frontend)/posts/page.client.tsx
  src/app/(frontend)/posts/page/[pageNumber]/page.client.tsx
  src/app/(frontend)/products/[slug]/page.client.tsx
  src/app/(frontend)/products/page.client.tsx
  src/app/(frontend)/products/page/[pageNumber]/page.client.tsx
  src/app/(frontend)/search/page.client.tsx
  src/app/(frontend)/services/[slug]/page.client.tsx
  src/app/(frontend)/services/page.client.tsx
  src/app/(frontend)/services/page/[pageNumber]/page.client.tsx
  src/app/(payload)/admin/importMap.js
  src/blocks/About/components/shared/components/ThemeEffect.tsx
  src/blocks/Contact/components/shared/ThemeEffect.tsx
  src/blocks/Team/components/shared/ThemeEffect.tsx
  src/blocks/shared/components/ThemeEffect.tsx
  src/collections/SiteSetting/index.ts
  src/collections/Tenants/index.ts
  src/endpoints/seed/collections/site-settings/index.ts
  src/endpoints/seed/collections/tenants/index.ts
  src/globals/Footer/components/shared/ThemeEffect.tsx
  src/globals/Header/components/shared/ThemeEffect.tsx
  src/payload-types.ts
  src/providers/DesignSystemProvider.tsx
  src/providers/HeaderTheme/index.tsx
  src/providers/Theme/InitTheme/index.tsx
  src/providers/Theme/ThemeSelector/index.tsx
  src/providers/Theme/ThemeSelector/types.ts
  src/providers/Theme/index.tsx
  src/providers/Theme/shared.ts
  src/providers/Theme/types.ts
  src/providers/index.tsx
  src/utilities/getCountryAccess.ts
  src/utilities/getSiteSettings.client.ts
  src/utilities/getSiteSettings.ts
  src/utilities/getTenant.client.tsx
  src/utilities/getTenant.ts
  tailwind.config.mjs
Labels: qa:verified

#233 fix: Duplicate Slug in the posts shouldn't be allowed
  src/collections/Categories.ts
  src/collections/Pages/hooks/ensureUniqueSlug.ts
  src/collections/Pages/index.ts
  src/collections/Posts/index.ts
  src/collections/Products/index.ts
  src/collections/Services/index.ts
  src/fields/slug/index.ts
Labels: qa:verified

#245 Refactor & Enhancement: Improve Theme Management and Global Styles
  docs/DESIGN_SYSTEM.md
  src/app/(frontend)/globals.css
  src/collections/SiteSetting/index.ts
  src/providers/DesignSystemProvider.tsx
  src/providers/Theme/InitTheme/index.tsx
  src/providers/Theme/ThemeSelector/index.tsx
  src/providers/Theme/index.tsx
  src/providers/Theme/shared.ts
  src/providers/Theme/types.ts
  src/themes/index.ts
  tailwind.config.mjs
Labels: qa:verified

#170 fix(ctasimple): added component stories ctasimple block
  src/blocks/CtaSimpleBlock/RenderCtaSimple.stories.tsx
  src/blocks/CtaSimpleBlock/RenderCtaSimple.tsx
  src/collections/Pages/index.ts
  src/payload-types.ts
Labels: qa:verified

#197 feat(gallery): added component gallery storybook
  src/blocks/Gallery/components/Gallery1/Component.tsx
  src/blocks/Gallery/components/Gallery3/Component.stories.tsx
  src/blocks/Gallery/components/Gallery4/Component.stories.tsx
  src/blocks/Gallery/components/Gallery4/Component.tsx
  src/blocks/Gallery/components/Gallery4/index.ts
  src/blocks/Gallery/components/Gallery5/Component.stories.tsx
  src/blocks/Gallery/components/Gallery5/Component.tsx
  src/blocks/Gallery/components/Gallery6/Component.stories.tsx
  src/blocks/Gallery/components/Gallery9/Component.stories.tsx
  src/blocks/Gallery/components/Gallery9/Component.tsx
Labels: qa:verified

#242 feat(RelatedPostComponent): add RelatedPost Stories with compatible theme
  src/blocks/RelatedPosts/Component.stories.tsx
  src/blocks/RelatedPosts/Component.tsx
  src/components/Card/index.tsx
Labels: qa:verified

#254 feat: FAQs storybook
  src/app/(frontend)/globals.css
  src/blocks/FAQ/components/FAQ2/Component.stories.tsx
  src/blocks/FAQ/components/FAQ3/Component.stories.tsx
  src/blocks/FAQ/components/FAQ3/Component.tsx
  src/blocks/FAQ/components/FAQ4/Component.stories.tsx
  src/blocks/FAQ/components/FAQ4/Component.tsx
  src/blocks/FAQ/components/FAQ5/Component.stories.tsx
  src/blocks/FAQ/components/FAQ6/Component.stories.tsx
  src/components/ui/accordion.tsx
  src/components/ui/button.tsx
Labels: qa:verified

#247 feat: Testimonial storybook
  src/blocks/Testimonial/components/Testimonial12/Component.stories.tsx
  src/blocks/Testimonial/components/Testimonial12/Component.tsx
  src/blocks/Testimonial/components/Testimonial14/Component.stories.tsx
  src/blocks/Testimonial/components/Testimonial14/Component.tsx
  src/blocks/Testimonial/components/Testimonial14/config.ts
  src/blocks/Testimonial/components/Testimonial15/Component.stories.tsx
  src/blocks/Testimonial/components/Testimonial15/Component.tsx
  src/blocks/Testimonial/components/Testimonial15/config.ts
  src/blocks/Testimonial/components/Testimonial16/Component.stories.tsx
  src/blocks/Testimonial/components/Testimonial16/Component.tsx
  src/blocks/Testimonial/components/Testimonial16/config.ts
  src/blocks/Testimonial/components/Testimonial17/Component.stories.tsx
  src/blocks/Testimonial/components/Testimonial17/Component.tsx
  src/blocks/Testimonial/components/Testimonial17/config.ts
  src/blocks/Testimonial/components/Testimonial18/Component.stories.tsx
  src/blocks/Testimonial/components/Testimonial18/Component.tsx
  src/blocks/Testimonial/components/Testimonial18/config.ts
  src/blocks/Testimonial/components/Testimonial19/Component.stories.tsx
  src/blocks/Testimonial/components/Testimonial19/Component.tsx
  src/blocks/Testimonial/components/Testimonial19/config.ts
  src/blocks/Testimonial/components/Testimonial4/Component.stories.tsx
  src/blocks/Testimonial/components/Testimonial4/Component.tsx
  src/blocks/Testimonial/components/Testimonial4/config.ts
  src/blocks/Testimonial/components/Testimonial6/Component.stories.tsx
  src/blocks/Testimonial/components/Testimonial6/Component.tsx
  src/blocks/Testimonial/components/Testimonial6/config.ts
  src/blocks/Testimonial/components/Testimonial7/Component.stories.tsx
  src/blocks/Testimonial/components/Testimonial7/Component.tsx
  src/blocks/Testimonial/components/Testimonial7/config.ts
  src/payload-types.ts
Labels: qa:verified

#260 Feat/hero block
  src/app/(payload)/admin/importMap.js
  src/fields/link.ts
  src/payload-types.ts
Labels: qa:verified

#261 Feat/team storybook
  src/blocks/Team/components/Team1/Component.tsx
  src/blocks/Team/components/Team2/Component.stories.tsx
  src/blocks/Team/components/Team2/Component.tsx
  src/blocks/Team/components/Team2/config.ts
  src/blocks/Team/components/Team3/Component.stories.tsx
  src/blocks/Team/components/Team3/Component.tsx
  src/blocks/Team/components/Team5/Component.stories.tsx
  src/blocks/Team/components/Team5/Component.tsx
  src/blocks/Team/components/Team6/Component.stories.tsx
  src/blocks/Team/components/Team6/Component.tsx
Labels: qa:verified

#224 test: Multi-Tenant Create + Search + Delete test cases
  .env.example
  .gitignore
  bun.lock
  cypress.config.ts
  cypress/e2e/smoke.cy.ts
  cypress/fixtures/tenant.json
  cypress/fixtures/toastMsg.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/types/cypress.d.ts
  cypress/utils/locators/payloadLocator.ts
  cypress/utils/pages/multiTenantPage.ts
  package.json
  playwright.config.ts
  playwright/tests/multiTenant.spec.ts
  playwright/utils/fixtures/tenantData.json
  playwright/utils/fixtures/toastMessage.json
  playwright/utils/pages/login.ts
  playwright/utils/pages/multiTenant.ts
Labels: qa:verified

#273 feat(267): Storybook Header
  src/globals/Header/components/Header3/Component.stories.tsx
  src/globals/Header/components/Header3/Component.tsx
  src/globals/Header/components/Header3/components/submenu/style1/Component.tsx
  src/globals/Header/components/Header3/components/submenu/style4/Component.tsx
  src/globals/Header/components/Header5/Component.stories.tsx
Labels: qa:verified

#266 feat(175): CTA Storybook
  src/blocks/CallToAction/components/CTA1/Component.stories.tsx
  src/blocks/CallToAction/components/CTA1/Component.tsx
  src/blocks/CallToAction/components/CTA10/Component.stories.tsx
  src/blocks/CallToAction/components/CTA10/Component.tsx
  src/blocks/CallToAction/components/CTA11/Component.stories.tsx
  src/blocks/CallToAction/components/CTA11/Component.tsx
  src/blocks/CallToAction/components/CTA15/Component.stories.tsx
  src/blocks/CallToAction/components/CTA15/Component.tsx
  src/blocks/CallToAction/components/CTA15/server/autogen.ts
  src/blocks/CallToAction/components/CTA15/server/index.ts
  src/blocks/CallToAction/components/CTA16/Component.stories.tsx
  src/blocks/CallToAction/components/CTA16/server/index.ts
  src/blocks/CallToAction/components/CTA17/Component.stories.tsx
  src/blocks/CallToAction/components/CTA17/Component.tsx
  src/blocks/CallToAction/components/CTA17/server/index.ts
  src/blocks/CallToAction/components/CTA3/Component.stories.tsx
  src/blocks/CallToAction/components/CTA3/Component.tsx
  src/blocks/CallToAction/components/CTA4/Component.stories.tsx
  src/blocks/CallToAction/components/CTA4/Component.tsx
  src/blocks/CallToAction/components/CTA5/Component.stories.tsx
  src/blocks/CallToAction/components/CTA5/Component.tsx
  src/blocks/CallToAction/components/CTA7/Component.stories.tsx
  src/blocks/CallToAction/components/CTA7/Component.tsx
  src/blocks/Team/components/Team2/config.ts
  src/blocks/VideoBlock/RenderVideo.tsx
  src/components/Media/ImageMedia/index.tsx
  src/components/Media/types.ts
  src/payload-types.ts
Labels: qa:verified
